# Generated by Django 3.2.3 on 2021-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TableB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TableC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TableD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_octet', models.IntegerField()),
                ('second_octet', models.IntegerField()),
                ('third_octet', models.IntegerField()),
                ('fourth_octet', models.IntegerField()),
                ('subnet_mask', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_octet', models.IntegerField()),
                ('second_octet', models.IntegerField()),
                ('third_octet', models.IntegerField()),
                ('fourth_octet', models.IntegerField()),
                ('subnet_mask', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_octet', models.IntegerField()),
                ('second_octet', models.IntegerField()),
                ('third_octet', models.IntegerField()),
                ('fourth_octet', models.IntegerField()),
                ('subnet_mask', models.IntegerField()),
                ('variable', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TableH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
