# Generated by Django 3.2.3 on 2021-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablea',
            name='column2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablea',
            name='column3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableb',
            name='column2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableb',
            name='column3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablec',
            name='column2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablec',
            name='column3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableg',
            name='column2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tableg',
            name='column3',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
