# Generated by Django 3.2.3 on 2021-06-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0003_auto_20210602_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableb',
            name='column3',
        ),
    ]
