# Generated by Django 3.2.3 on 2021-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0004_remove_tableb_column3'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablec',
            name='column4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
