# Generated by Django 3.2.3 on 2021-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0005_tablec_column4'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableh',
            name='column2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
