# Generated by Django 3.2.3 on 2021-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0007_auto_20210604_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablec',
            name='column4',
            field=models.CharField(blank=True, choices=[('Value 1', ''), ('Value 2', '')], max_length=255, null=True),
        ),
    ]
