# Generated by Django 3.2.3 on 2021-06-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0008_alter_tablec_column4'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabled',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tablee',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
