# Generated by Django 3.2.3 on 2021-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplookup', '0009_auto_20210605_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablec',
            name='column4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
